sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
node_js:
  - "8"
before_script:
  - rm -rf ./coverage
install:
  - npm i -g codecov
  - npm i
script:
  - npm run lint
  - npm run build
  - npm run coverage
  - codecov
