CREATE TABLE IF NOT EXISTS public."user" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text UNIQUE NOT NULL,
  "password" text,
  "activated" boolean NOT NULL DEFAULT false,
  "credit" integer NOT NULL DEFAULT 0,
  "createdAt" timestamp with time zone,
  "updatedAt" timestamp with time zone,
  "deletedAt" timestamp with time zone
);
