#!/bin/bash

status=0
lernaPackagesPath=./packages

build() {
  if [[ $1 == ornn ]] || [[ $1 == ornn-* ]]; then
    packageName=$1
  else
    packageName=ornn-$1
  fi

  # throw error if the ornn-${name} is not found in packages dir
  # except for the ornn package itself
  if [ ! -d "$lernaPackagesPath/$packageName" ]; then
    echo "Error: Invalid package: '$packageName'."
    exit 1
  fi

  packagePath=$lernaPackagesPath/$packageName

  echo "Cleaning previous build:" $packageName...
  rm -rf $packagePath/lib
  echo "Cleaning previous build:" $packageName...Done!
  echo

  echo "Building:" $packageName...
  NODE_ENV=production babel $packagePath/src --out-dir $packagePath/lib

  if [ $? -eq 0 ]; then
    echo "Building:" $packageName...Done!
  else
    status=1
    echo "Building:" $packageName...Failed!
  fi
}

# if cli did not supply any argument then build all
if [ -z "$1" ]; then
  for path in $(ls -d ./packages/*/);
  do
    path=${path::-1}
    build ${path:11}
  done
else
  build $1
fi

echo
exit $status
