#!/bin/bash

status=0
lernaPackagesPath=./packages

lint() {
  if [[ $1 == ornn ]] || [[ $1 == ornn-* ]]; then
    packageName=$1
  else
    packageName=ornn-$1
  fi

  # throw error if the ornn-${name} is not found in packages dir
  # except for the ornn package itself
  if [ ! -d "$lernaPackagesPath/$packageName" ]; then
    echo "Error: Invalid package: '$packageName'."
    exit 1
  fi

  packagePath=$lernaPackagesPath/$packageName

  echo "Linting:" $packageName...
  eslint $packagePath/src $packagePath/test --ext .js,.mjs

  if [ $? -eq 0 ]; then
    echo "Linting:" $packageName...Done!
  else
    status=1
    echo "Linting:" $packageName...Failed!
  fi
}

# if cli did not supply any argument then lint all
if [ -z "$1" ]; then
  for path in $(ls -d ./packages/*/);
  do
    path=${path::-1}
    lint ${path:11}
  done
else
  lint $1
fi

echo
exit $status
