#!/bin/bash

status=0
lernaPackagesPath=./packages

format() {
  if [[ $1 == ornn ]] || [[ $1 == ornn-* ]]; then
    packageName=$1
  else
    packageName=ornn-$1
  fi

  # throw error if the ornn-${name} is not found in packages dir
  # except for the ornn package itself
  if [ ! -d "$lernaPackagesPath/$packageName" ]; then
    echo "Error: Invalid package: '$packageName'."
    exit 1
  fi

  packagePath=$lernaPackagesPath/$packageName

  echo "Formatting:" $packageName...
  prettier "{$packagePath/src,$packagePath/test}/**/*.{js,mjs,json,md}" --write

  if [ $? -eq 0 ]; then
    echo "Formatting:" $packageName...Done!
  else
    status=1
    echo "Formatting:" $packageName...Failed!
  fi
}

# if cli did not supply any argument then format all
if [ -z "$1" ]; then
  for path in $(ls -d ./packages/*/);
  do
    path=${path::-1}
    format ${path:11}
  done
else
  format $1
fi

echo
exit $status
