import CreateTable from '../src/createTable';

test('the sql', () => {
  const table = new CreateTable({
    tableName: 'user',
    columns: [
      {
        name: 'id',
        type: 'integer',
        identity: true,
        primaryKey: true,
      },
      {
        name: 'email',
        type: 'text',
        required: true,
        unique: true,
      },
    ],
  });

  expect(table.tableName).toBe('user');
  const sql = `CREATE TABLE "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL UNIQUE
);`;
  expect(table.sql).toBe(sql);
});
